# Generated by Django 5.2.9 on 2026-01-02 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0007_creditcard_image_creditcard_image_url'),
        ('offers', '0008_bankspecificcardassociation_bankspecificcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_expiring_offers', models.BooleanField(default=True)),
                ('email_new_offers', models.BooleanField(default=True)),
                ('email_savings_opportunities', models.BooleanField(default=True)),
                ('email_scheduled_reminders', models.BooleanField(default=True)),
                ('email_chatbot_suggestions', models.BooleanField(default=False)),
                ('in_app_expiring_offers', models.BooleanField(default=True)),
                ('in_app_new_offers', models.BooleanField(default=True)),
                ('in_app_savings_opportunities', models.BooleanField(default=True)),
                ('in_app_scheduled_reminders', models.BooleanField(default=True)),
                ('in_app_chatbot_suggestions', models.BooleanField(default=True)),
                ('email_frequency', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DAILY', 'Daily Digest'), ('WEEKLY', 'Weekly Digest')], default='DAILY', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EXPIRING_OFFER', 'Expiring Offer'), ('NEW_OFFER', 'New Offer'), ('SAVINGS_OPPORTUNITY', 'Savings Opportunity'), ('SCHEDULED_REMINDER', 'Scheduled Purchase Reminder'), ('CHATBOT_SUGGESTION', 'Chatbot Suggestion'), ('CARD_RECOMMENDATION', 'Card Recommendation'), ('SYSTEM', 'System Notification')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.bank')),
                ('related_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.creditcard')),
                ('related_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_63f199_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
