# Generated by Django 5.2.9 on 2026-01-02 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0007_creditcard_image_creditcard_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('GROCERIES', 'Groceries'), ('DINING', 'Dining'), ('SHOPPING', 'Shopping'), ('FUEL', 'Fuel'), ('TRAVEL', 'Travel'), ('ENTERTAINMENT', 'Entertainment'), ('UTILITIES', 'Utilities'), ('ONLINE_SHOPPING', 'Online Shopping'), ('OTHER', 'Other')], max_length=50)),
                ('scheduled_date', models.DateTimeField(help_text='When the purchase is planned')),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, help_text='Location/city for the purchase', max_length=255, null=True)),
                ('merchant_preference', models.CharField(blank=True, help_text='Preferred merchant/store', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recommended_merchants', models.JSONField(blank=True, default=list, help_text='List of merchants with active offers')),
                ('active_offers', models.JSONField(blank=True, default=list, help_text='List of relevant offers for this purchase')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recommended_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for_purchases', to='cards.creditcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduled_purchases',
                'ordering': ['scheduled_date'],
                'indexes': [models.Index(fields=['user', 'scheduled_date'], name='scheduled_p_user_id_5efab3_idx'), models.Index(fields=['user', 'status'], name='scheduled_p_user_id_8472da_idx')],
            },
        ),
    ]
