# Generated by Django 5.2.9 on 2025-12-17 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('merchant_type', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('HOTEL', 'Hotel'), ('RETAIL', 'Retail Store'), ('E_COMMERCE', 'E-commerce'), ('FUEL_STATION', 'Fuel Station'), ('SUPERMARKET', 'Supermarket'), ('TRAVEL', 'Travel Agency'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='merchant_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'merchants',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('offer_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('CASHBACK', 'Cashback'), ('REWARD_MULTIPLIER', 'Reward Multiplier'), ('EMI', 'EMI Offer'), ('WELCOME_BONUS', 'Welcome Bonus'), ('FEE_WAIVER', 'Fee Waiver')], max_length=50)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cashback_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('redemption_process', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scraping_source', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='cards.bank')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='cards.creditcard')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='offers.merchant')),
            ],
            options={
                'db_table': 'offers',
                'ordering': ['-valid_to'],
            },
        ),
        migrations.CreateModel(
            name='UserOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ACTIVATED', 'Activated'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
            ],
            options={
                'db_table': 'user_offers',
            },
        ),
    ]
