# Generated by Django 5.2.9 on 2025-12-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='city',
            field=models.CharField(choices=[('KARACHI', 'Karachi'), ('LAHORE', 'Lahore'), ('ISLAMABAD', 'Islamabad'), ('RAWALPINDI', 'Rawalpindi'), ('FAISALABAD', 'Faisalabad'), ('MULTAN', 'Multan'), ('HYDERABAD', 'Hyderabad'), ('PESHAWAR', 'Peshawar'), ('QUETTA', 'Quetta'), ('GUJRANWALA', 'Gujranwala'), ('SIALKOT', 'Sialkot'), ('BAHAWALPUR', 'Bahawalpur'), ('SARGODHA', 'Sargodha'), ('SUKKUR', 'Sukkur'), ('LARKANA', 'Larkana'), ('SHEIKHUPURA', 'Sheikhupura'), ('MIRPUR_KHAS', 'Mirpur Khas'), ('RAHIM_YAR_KHAN', 'Rahim Yar Khan'), ('KASUR', 'Kasur'), ('GUJRAT', 'Gujrat'), ('OTHER', 'Other')], default='KARACHI', max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchant_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('HOTEL', 'Hotel'), ('RETAIL', 'Retail Store'), ('E_COMMERCE', 'E-commerce'), ('FUEL_STATION', 'Fuel Station'), ('SUPERMARKET', 'Supermarket'), ('TRAVEL', 'Travel Agency'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('AUTOMOTIVE', 'Automotive'), ('FASHION', 'Fashion & Apparel'), ('ELECTRONICS', 'Electronics'), ('HOME', 'Home & Furniture'), ('BEAUTY', 'Beauty & Salon'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['city'], name='merchants_city_640086_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['merchant_type'], name='merchants_merchan_b81171_idx'),
        ),
    ]
