# Generated by Django 5.2.9 on 2025-12-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_merchant_area_merchant_is_verified_merchant_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='city',
            field=models.CharField(choices=[('ALL_PAKISTAN', 'All Pakistan'), ('KARACHI', 'Karachi'), ('LAHORE', 'Lahore'), ('ISLAMABAD', 'Islamabad'), ('RAWALPINDI', 'Rawalpindi'), ('FAISALABAD', 'Faisalabad'), ('MULTAN', 'Multan'), ('HYDERABAD', 'Hyderabad'), ('PESHAWAR', 'Peshawar'), ('QUETTA', 'Quetta'), ('GUJRANWALA', 'Gujranwala'), ('SIALKOT', 'Sialkot'), ('BAHAWALPUR', 'Bahawalpur'), ('SARGODHA', 'Sargodha'), ('SUKKUR', 'Sukkur'), ('LARKANA', 'Larkana'), ('SHEIKHUPURA', 'Sheikhupura'), ('MIRPUR_KHAS', 'Mirpur Khas'), ('RAHIM_YAR_KHAN', 'Rahim Yar Khan'), ('KASUR', 'Kasur'), ('GUJRAT', 'Gujrat'), ('OTHER', 'Other')], default='KARACHI', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('DISCOUNT', 'Discount'), ('CASHBACK', 'Cashback'), ('REWARD_MULTIPLIER', 'Reward Multiplier'), ('EMI', 'EMI Offer'), ('WELCOME_BONUS', 'Welcome Bonus'), ('FEE_WAIVER', 'Fee Waiver'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
