# Generated by Django 5.2.9 on 2025-12-23 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_usercard_options_usercard_card_network'),
        ('offers', '0004_alter_merchant_city_alter_offer_offer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeekabooCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.peekaboocategory')),
            ],
            options={
                'verbose_name_plural': 'Peekaboo Categories',
                'db_table': 'peekaboo_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PeekabooDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.BigIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_entity_id', models.BigIntegerField(blank=True, null=True)),
                ('target_entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('target_entity_logo', models.URLField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_redeemable', models.BooleanField(default=False)),
                ('redeemable_count', models.IntegerField(default=0)),
                ('redeemed_count', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('target_branches', models.JSONField(blank=True, default=dict)),
                ('order_type', models.CharField(blank=True, max_length=50, null=True)),
                ('powered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peekaboo_deals', to='cards.bank')),
            ],
            options={
                'db_table': 'peekaboo_deals',
                'ordering': ['-end_date', '-created_at'],
                'indexes': [models.Index(fields=['deal_id'], name='peekaboo_de_deal_id_95a1b0_idx'), models.Index(fields=['city', 'is_expired'], name='peekaboo_de_city_b2ffc6_idx'), models.Index(fields=['category', 'is_active'], name='peekaboo_de_categor_82e892_idx'), models.Index(fields=['end_date'], name='peekaboo_de_end_dat_574f3c_idx')],
            },
        ),
    ]
