# Generated by Django 5.2.9 on 2025-12-23 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_usercard_options_usercard_card_network'),
        ('offers', '0005_add_peekaboo_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peekaboodeal',
            name='target_entity_id',
        ),
        migrations.AddField(
            model_name='peekaboodeal',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peekaboo_deals', to='cards.creditcard'),
        ),
        migrations.AddField(
            model_name='peekaboodeal',
            name='raw_entity_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Raw entity ID from Peekaboo API', null=True),
        ),
        migrations.CreateModel(
            name='PeekabooEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_entity_id', models.BigIntegerField(db_index=True, unique=True)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('is_applied_allowed', models.BooleanField(default=False)),
                ('is_membership_allowed', models.BooleanField(default=False)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'peekaboo_entities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['source_entity_id'], name='peekaboo_en_source__5e9cb0_idx'), models.Index(fields=['name'], name='peekaboo_en_name_2a68ef_idx')],
            },
        ),
        migrations.AddField(
            model_name='peekaboodeal',
            name='target_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='offers.peekabooentity'),
        ),
        migrations.AddIndex(
            model_name='peekaboodeal',
            index=models.Index(fields=['target_entity_id'], name='peekaboo_de_target__0b13d4_idx'),
        ),
    ]
