# Generated by Django 5.2.9 on 2025-12-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_usercard_options_usercard_card_network'),
        ('offers', '0006_add_peekaboo_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peekaboodeal',
            name='card',
        ),
        migrations.AddField(
            model_name='peekaboodeal',
            name='associations',
            field=models.JSONField(blank=True, default=list, help_text='Card associations from Peekaboo API'),
        ),
        migrations.AddField(
            model_name='peekaboodeal',
            name='linked_cards',
            field=models.ManyToManyField(blank=True, help_text='Credit cards this deal applies to', related_name='peekaboo_deals', to='cards.creditcard'),
        ),
        migrations.AddField(
            model_name='peekaboodeal',
            name='source_entity_id',
            field=models.BigIntegerField(blank=True, help_text='Source entity ID (bank) from API', null=True),
        ),
        migrations.AddField(
            model_name='peekaboodeal',
            name='source_entity_logo',
            field=models.URLField(blank=True, help_text='Source entity logo (bank) from API', null=True),
        ),
        migrations.AddField(
            model_name='peekaboodeal',
            name='source_entity_name',
            field=models.CharField(blank=True, help_text='Source entity name (bank) from API', max_length=255, null=True),
        ),
    ]
