# Generated by Django 5.2.9 on 2026-01-20 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_creditcard_image_creditcard_image_url'),
        ('offers', '0008_bankspecificcardassociation_bankspecificcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peekaboo_entity_id', models.BigIntegerField(db_index=True, help_text='Entity ID from Peekaboo URL', unique=True)),
                ('peekaboo_slug', models.CharField(db_index=True, help_text='Slug from Peekaboo URL', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_banks', to='cards.bank')),
            ],
            options={
                'db_table': 'partner_banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_cards', to='cards.creditcard')),
                ('partner_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='offers.partnerbank')),
            ],
            options={
                'db_table': 'partner_cards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_logo', models.URLField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('partner_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='offers.partnerbank')),
                ('partner_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='offers.partnercard')),
            ],
            options={
                'db_table': 'partner_offers',
                'ordering': ['-valid_to', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='partnerbank',
            index=models.Index(fields=['peekaboo_entity_id'], name='partner_ban_peekabo_03b2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerbank',
            index=models.Index(fields=['peekaboo_slug'], name='partner_ban_peekabo_6f22c8_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercard',
            index=models.Index(fields=['partner_bank'], name='partner_car_partner_a0eb76_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercard',
            index=models.Index(fields=['name'], name='partner_car_name_e46cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='partneroffer',
            index=models.Index(fields=['partner_bank'], name='partner_off_partner_3b81f2_idx'),
        ),
        migrations.AddIndex(
            model_name='partneroffer',
            index=models.Index(fields=['partner_card'], name='partner_off_partner_cab925_idx'),
        ),
        migrations.AddIndex(
            model_name='partneroffer',
            index=models.Index(fields=['city'], name='partner_off_city_1c8753_idx'),
        ),
        migrations.AddIndex(
            model_name='partneroffer',
            index=models.Index(fields=['category'], name='partner_off_categor_a97973_idx'),
        ),
        migrations.AddIndex(
            model_name='partneroffer',
            index=models.Index(fields=['is_active', 'is_expired'], name='partner_off_is_acti_5ae822_idx'),
        ),
    ]
