# Generated by Django 5.2.9 on 2026-01-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_creditcard_image_creditcard_image_url'),
        ('offers', '0009_partnerbank_partnercard_partneroffer_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='partnercard',
            index=models.Index(fields=['credit_card'], name='partner_car_credit__32be46_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercard',
            index=models.Index(fields=['is_active'], name='partner_car_is_acti_61a2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercard',
            index=models.Index(fields=['partner_bank', 'is_active', 'slug'], name='partner_car_partner_5742a0_idx'),
        ),
        migrations.AddIndex(
            model_name='partneroffer',
            index=models.Index(fields=['is_active', 'is_expired', 'city'], name='partner_off_is_acti_bb5e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='partneroffer',
            index=models.Index(fields=['partner_card', 'is_active', 'is_expired'], name='partner_off_partner_21f8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='partneroffer',
            index=models.Index(fields=['source_url'], name='partner_offers_source_url_idx'),
        ),
    ]
