# Generated by Django 5.2.9 on 2026-01-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_partnercard_partner_car_credit__32be46_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneroffer',
            name='available_on_cards',
            field=models.ManyToManyField(blank=True, help_text="Cards this offer is available on (from 'Available On' section on card deal page)", related_name='available_offers', to='offers.partnercard'),
        ),
    ]
