# Generated by Django 5.2.9 on 2026-01-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_partneroffer_available_on_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partneroffer',
            name='available_on_cards',
        ),
    ]
