# Generated by Django 5.2.9 on 2026-01-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_remove_partneroffer_available_on_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercard',
            name='peekaboo_association_id',
            field=models.BigIntegerField(blank=True, help_text='Association ID from Peekaboo API', null=True),
        ),
        migrations.AddField(
            model_name='partnercard',
            name='peekaboo_association_type_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Association type ID from Peekaboo API', null=True),
        ),
    ]
