# Generated by Django 5.2.9 on 2026-01-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_partnercard_peekaboo_association_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneroffer',
            name='available_on_cards',
            field=models.ManyToManyField(blank=True, help_text="Cards this offer is available on (from 'associations' array in Peekaboo API)", related_name='available_offers', to='offers.partnercard'),
        ),
    ]
