# Generated by Django 5.2.9 on 2026-01-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_partneroffer_available_on_cards'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='partnercard',
            name='partner_car_credit__32be46_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnercard',
            name='partner_car_is_acti_61a2a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='partnercard',
            name='partner_car_partner_5742a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='partneroffer',
            name='partner_off_is_acti_bb5e9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='partneroffer',
            name='partner_off_partner_21f8e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='partneroffer',
            name='partner_offers_source_url_idx',
        ),
        migrations.RemoveField(
            model_name='partnercard',
            name='peekaboo_association_id',
        ),
        migrations.RemoveField(
            model_name='partnercard',
            name='peekaboo_association_type_id',
        ),
    ]
