# Generated by Django 5.2.9 on 2026-01-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_remove_partnercard_partner_car_credit__32be46_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercard',
            name='peekaboo_association_id',
            field=models.BigIntegerField(blank=True, help_text='Association ID from Peekaboo API for this card', null=True),
        ),
        migrations.AddField(
            model_name='partnercard',
            name='peekaboo_association_type_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Association Type ID from Peekaboo API for this card', null=True),
        ),
    ]
