# Generated by Django 5.2.9 on 2025-12-17 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapinglog',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.bank'),
        ),
    ]
