# Generated by Django 5.2.9 on 2025-12-18 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
        ('cards', '0003_alter_bank_options_bank_atm_network_bank_bank_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapinglog',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.bank'),
        ),
        migrations.AlterField(
            model_name='scrapinglog',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
