# Generated by Django 5.2.9 on 2025-12-30 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0005_creditcard_peekaboo_association_type_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('merchant', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('DINING', 'Dining'), ('GROCERIES', 'Groceries'), ('FUEL', 'Fuel'), ('TRAVEL', 'Travel'), ('SHOPPING', 'Shopping'), ('ENTERTAINMENT', 'Entertainment'), ('UTILITIES', 'Utilities'), ('ONLINE_SHOPPING', 'Online Shopping'), ('INTERNATIONAL', 'International'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('reward_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('potential_reward', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recommended_card_id', models.IntegerField(blank=True, null=True)),
                ('missed_savings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statement_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('user_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cards.usercard')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='transaction_user_id_059bf9_idx'), models.Index(fields=['user', 'category'], name='transaction_user_id_cfabf3_idx')],
            },
        ),
    ]
