# Generated by Django 5.2.9 on 2025-12-17 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bank_logos/')),
                ('website', models.URLField()),
                ('support_email', models.EmailField(max_length=254)),
                ('support_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('card_type', models.CharField(choices=[('CREDIT', 'Credit Card'), ('DEBIT', 'Debit Card'), ('BOTH', 'Both Credit & Debit'), ('PREMIUM', 'Premium Cards Only'), ('PLATINUM', 'Platinum Cards Only'), ('GOLD', 'Gold Cards Only')], max_length=20)),
                ('annual_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credit_limit_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_limit_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reward_points_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('cashback_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('welcome_bonus', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scraping_url', models.URLField(blank=True, null=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.bank')),
            ],
            options={
                'db_table': 'credit_cards',
            },
        ),
        migrations.CreateModel(
            name='CardRewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DINING', 'Dining'), ('GROCERIES', 'Groceries'), ('FUEL', 'Fuel'), ('TRAVEL', 'Travel'), ('SHOPPING', 'Shopping'), ('ENTERTAINMENT', 'Entertainment'), ('UTILITIES', 'Utilities'), ('ONLINE_SHOPPING', 'Online Shopping'), ('INTERNATIONAL', 'International'), ('OTHER', 'Other')], max_length=50)),
                ('reward_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_categories', to='cards.creditcard')),
            ],
            options={
                'db_table': 'card_reward_categories',
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number_last4', models.CharField(max_length=4)),
                ('expiry_date', models.DateField()),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.creditcard')),
            ],
            options={
                'db_table': 'user_cards',
            },
        ),
    ]
