# Generated by Django 5.2.9 on 2025-12-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='bank',
            name='atm_network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_type',
            field=models.CharField(choices=[('COMMERCIAL', 'Commercial Bank'), ('ISLAMIC', 'Islamic Bank'), ('GOVERNMENT', 'Government Bank'), ('INTERNATIONAL', 'International Bank'), ('SPECIALIZED', 'Specialized Bank')], default='COMMERCIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='bank',
            name='digital_banking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='headquarters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='mobile_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='total_branches',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
