# Generated by Django 5.2.9 on 2025-12-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_bank_options_bank_atm_network_bank_bank_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercard',
            options={'ordering': ['-is_primary', '-linked_at']},
        ),
        migrations.AddField(
            model_name='usercard',
            name='card_network',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('UNIONPAY', 'UnionPay'), ('DISCOVER', 'Discover'), ('OTHER', 'Other')], default='VISA', max_length=20),
        ),
    ]
