# Generated by Django 5.2.9 on 2025-12-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_usercard_options_usercard_card_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='peekaboo_association_type_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Peekaboo associationTypeId for this card', null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='peekaboo_card_slug',
            field=models.CharField(blank=True, db_index=True, help_text='Peekaboo card slug (e.g., visa-infinite-debit-card)', max_length=255, null=True),
        ),
    ]
