# Generated by Django 5.2.9 on 2026-01-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_bank_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='card_images/'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of card image from bank website', null=True),
        ),
    ]
